version: '2'

services:
  kafka_monitor:
    build:
      context: .
      dockerfile: docker/kafka-monitor/Dockerfile
    image: umo-kafka-monitor:latest
    depends_on:
      - kafka
      - redis
    restart: always
  redis_monitor:
    build:
      context: .
      dockerfile: docker/redis-monitor/Dockerfile
    image: umo-redis-monitor:latest
    depends_on:
      - kafka
      - redis
      - zookeeper
    restart: always
  crawler:
    build:
      context: .
      dockerfile: docker/crawler/Dockerfile
    image: umo-crawler:latest
    depends_on:
      - kafka
      - redis
      - zookeeper
    restart: always
  rest:
    build:
      context: .
      dockerfile: docker/rest/Dockerfile
    image: umo-rest:latest
    depends_on:
      - kafka
      - redis
    restart: always
    ports:
      - "5343:5343"
  webpage_pool:
    build:
      context: .
      dockerfile: ./docker/webpage-pool/Dockerfile
    image: umo-webpage-pool:latest
    depends_on:
      - kafka
      - redis
    restart: always
  redis:
    image: redis
    ports:
      - "6379"
    restart: always
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
    restart: always
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    restart: always
